# About the project

Many birds are reported to add green nest material to their nest. These green material could be leaves, sprigs and branches of aromatic herbs and trees, showing some preferential selection of the material. Some species bring these additional material even after the completion of nest building. This has led researchers to understand the functional benefits of this behaviour through both observation and experiments. This behaviour has been reviewed in detail in @dubiec2013 and @scott-baumann2015. We wanted to quantitatively synthesize the experimental studies investigating the function of green nest material and to test some of the several hypothesis suggested in the field. We conducted a systematic review and meta-analysis to do so.

Our project wanted to understand if the addition of green material to the nest have any benefits across bird species that show this behaviour?

There are many hypothesis suggested for how the this behaviour could be beneficial to the birds. Three common hypothesis suggested are courtship hypothesis, nest protection hypothesis and drug hypothesis. We wanted to understand what the support for any of these hypothesis. We wanted to understand if this behaviour increases their reproductive success (therefore showing support to courtship hypothesis suggested in the literature)? Does the addition of green nest material by birds lead to protective effect and/or increased health benefits for the nestling (therefore showing support to nest protection or drug hypothesis. We combine the two and call it parental care hypothesis)
